services:
  db:
    image: mysql:8.0.38
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: chat_app
    ports:
      - "3306:3306"
    volumes:
      - ./schema/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - app_network

  redis:
    image: redis:6.2-alpine
    hostname: redis
    command: redis-server --bind 0.0.0.0
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB;FLUSHALL
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network

  redisinsight:
    image: redislabs/redisinsight:1.6.3
    ports:
      - 8001:8001
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: